name: Release CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint command
        run: yarn lint
  test:
    needs: [lint]
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
  # release:
  #   needs: [lint]
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, '[skip ci]')"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #     - name: Cache node modules
  #       uses: c-hive/gha-yarn-cache@v1
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Release
  #       run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         GIT_AUTHOR_NAME: "kaaaxcreatorsBOT"
  #         GIT_AUTHOR_EMAIL: "bernd@kaaaxcreators.de"
  #         GIT_COMMITTER_NAME: "kaaaxcreatorsBOT"
  #         GIT_COMMITTER_EMAIL: "bernd@kaaaxcreators.de"
